version: 2.1

workflows:
  build-and-test-all:
    jobs:
      # CircleCI's current generation of Node images, cimg/node, allow you to leave the
      # patch version unpinned, but require you to specify the minor version. The one
      # exception is cimg/node:current, which will always give us the latest release in
      # the latest major version-- and the latest major version is where it's most likely
      # that there would be a new minor version, anyway.
      - build-test-linux:
          name: latest Node version
          docker-image: cimg/node:current
          run-lint: true
      - build-test-linux:
          name: Node 16.3
          docker-image: cimg/node:16.3
      - build-test-linux:
          name: Node 15.14
          docker-image: cimg/node:15.14
      - build-test-linux:
          name: Node 14.17
          docker-image: cimg/node:14.17
      - build-test-linux:
          name: Node 13.14
          docker-image: cimg/node:13.14
      - build-test-linux:
          name: Node 12.22
          docker-image: cimg/node:12.22

jobs:
  build-test-linux:
    parameters:
      run-lint:
        type: boolean
        default: false
      docker-image:
        type: string
    docker:
      - image: <<parameters.docker-image>>
      - image: amazon/dynamodb-local
    steps:
      - checkout
      - run: echo "Node version:" `node --version`
      - run: npm install
      - run:
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: npm run lint
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
