publications:
  - url: https://www.npmjs.com/package/launchdarkly-node-server-sdk-dynamodb
    description: npm

releasableBranches:
  - name: master
    description: 3.x
  - name: 2.x
  - name: 1.x

template:
  name: npm
  skip:
    - test  # Running the unit tests would require installing DynamoDB. They've already been run in CI.

documentation:
  githubPages: true
  title: LaunchDarkly Server-Side Node SDK DynamoDB Integration
