version: 2

publications:
  - url: https://www.npmjs.com/package/launchdarkly-node-server-sdk-dynamodb
    description: npm

branches:
  - name: main
    description: 4.x
  - name: 3.x
  - name: 2.x
  - name: 1.x

jobs:
  - docker:
      image: node:12-buster
    template:
      name: npm
      skip:
        - test  # Running the unit tests would require installing DynamoDB. They've already been run in CI.

documentation:
  gitHubPages: true
  title: LaunchDarkly Server-Side Node SDK DynamoDB Integration
